version: '3'

services:
  python:
    container_name: tracker_bot
    build:
      context: .
      dockerfile: python.dockerfile
    depends_on:
      - mariadb
    volumes:
      - ./storage/data/logs:/home/app/storage/data/logs
      - ./storage/data/cache:/home/app/storage/data/cache
    networks:
      - tracker_network
    command: "run:all"
  mariadb:
    container_name: tracker_database
    image: mariadb:10.7.3
    volumes:
      - ./storage/data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_HOST_PORT}:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      retries: 3
      timeout: 5s
    networks:
      - tracker_network
networks:
  tracker_network:
    name: tracker_network
    driver: bridge
